export interface Place {
  name: string;
  lat: number;
  lng: number;
  region: string;
}

export const REGION_COLORS: Record<string, string> = {
  "Ladakh & Kashmir": "#6E9DC6",
  "Himachal & Spiti": "#4E7C59",
  Uttarakhand: "#3D6B86",
  "Rajasthan & Desert": "#B25A3C",
  "Plains & Heritage": "#7C5237",
  "Beaches & South": "#2E4632",
  Islands: "#C86B45",
};

export const PLACES: Place[] = [
  { name: "Leh", lat: 34.16, lng: 77.58, region: "Ladakh & Kashmir" },
  { name: "Srinagar", lat: 34.08, lng: 74.8, region: "Ladakh & Kashmir" },
  { name: "Sonmarg", lat: 34.3, lng: 75.3, region: "Ladakh & Kashmir" },
  { name: "Gulmarg", lat: 34.05, lng: 74.38, region: "Ladakh & Kashmir" },
  { name: "Pahalgam", lat: 34.14, lng: 75.33, region: "Ladakh & Kashmir" },
  { name: "Vaishno Devi", lat: 33.03, lng: 74.94, region: "Ladakh & Kashmir" },
  { name: "Manali", lat: 32.24, lng: 77.18, region: "Himachal & Spiti" },
  { name: "Shimla", lat: 31.1, lng: 77.18, region: "Himachal & Spiti" },
  { name: "Dharamshala", lat: 32.22, lng: 76.32, region: "Himachal & Spiti" },
  { name: "McLeodganj", lat: 32.24, lng: 76.32, region: "Himachal & Spiti" },
  { name: "Dalhousie", lat: 32.54, lng: 75.97, region: "Himachal & Spiti" },
  { name: "Khajjiar", lat: 32.54, lng: 76.04, region: "Himachal & Spiti" },
  { name: "Kasol", lat: 32.01, lng: 77.31, region: "Himachal & Spiti" },
  { name: "Kullu", lat: 31.96, lng: 77.11, region: "Himachal & Spiti" },
  { name: "Solang", lat: 32.31, lng: 77.15, region: "Himachal & Spiti" },
  { name: "Rohtang Pass", lat: 32.37, lng: 77.25, region: "Himachal & Spiti" },
  { name: "Tirthan Valley", lat: 31.59, lng: 77.44, region: "Himachal & Spiti" },
  { name: "Spiti", lat: 32.25, lng: 78.0, region: "Himachal & Spiti" },
  { name: "Mussoorie", lat: 30.45, lng: 78.08, region: "Uttarakhand" },
  { name: "Nainital", lat: 29.4, lng: 79.46, region: "Uttarakhand" },
  { name: "Rishikesh", lat: 30.08, lng: 78.29, region: "Uttarakhand" },
  { name: "Haridwar", lat: 29.95, lng: 78.16, region: "Uttarakhand" },
  { name: "Dehradun", lat: 30.32, lng: 78.03, region: "Uttarakhand" },
  { name: "Kedarnath", lat: 30.73, lng: 79.06, region: "Uttarakhand" },
  { name: "Jaipur", lat: 26.91, lng: 75.78, region: "Rajasthan & Desert" },
  { name: "Jaisalmer", lat: 26.91, lng: 70.91, region: "Rajasthan & Desert" },
  { name: "Jodhpur", lat: 26.23, lng: 73.02, region: "Rajasthan & Desert" },
  { name: "Mount Abu", lat: 24.59, lng: 72.71, region: "Rajasthan & Desert" },
  { name: "Delhi", lat: 28.61, lng: 77.23, region: "Plains & Heritage" },
  { name: "Agra", lat: 27.18, lng: 78.02, region: "Plains & Heritage" },
  { name: "Varanasi", lat: 25.31, lng: 82.97, region: "Plains & Heritage" },
  { name: "Ayodhya", lat: 26.79, lng: 82.19, region: "Plains & Heritage" },
  { name: "Mumbai", lat: 19.07, lng: 72.87, region: "Beaches & South" },
  { name: "Matheran", lat: 18.98, lng: 73.27, region: "Beaches & South" },
  { name: "Lonavala", lat: 18.75, lng: 73.41, region: "Beaches & South" },
  { name: "Malshej Ghat", lat: 19.34, lng: 73.8, region: "Beaches & South" },
  { name: "Tamhini Ghat", lat: 18.6, lng: 73.45, region: "Beaches & South" },
  { name: "Panshet", lat: 18.37, lng: 73.53, region: "Beaches & South" },
  { name: "Bhimashankar", lat: 19.07, lng: 73.55, region: "Beaches & South" },
  { name: "Trimbakeshwar", lat: 19.93, lng: 73.53, region: "Beaches & South" },
  { name: "Shirdi", lat: 19.77, lng: 74.47, region: "Plains & Heritage" },
  { name: "Nashik", lat: 19.99, lng: 73.79, region: "Beaches & South" },
  { name: "Kalsubai", lat: 19.6, lng: 73.7, region: "Beaches & South" },
  { name: "Harishchandragad", lat: 19.39, lng: 73.74, region: "Beaches & South" },
  { name: "Goa", lat: 15.49, lng: 73.82, region: "Beaches & South" },
  { name: "Dudhsagar", lat: 15.31, lng: 74.31, region: "Beaches & South" },
  { name: "Konkan", lat: 16.5, lng: 73.5, region: "Beaches & South" },
  { name: "Mahabaleshwar", lat: 17.93, lng: 73.66, region: "Beaches & South" },
  { name: "Bangalore", lat: 12.97, lng: 77.59, region: "Beaches & South" },
  { name: "Kochi", lat: 9.93, lng: 76.27, region: "Beaches & South" },
  { name: "Munnar", lat: 10.08, lng: 77.06, region: "Beaches & South" },
  { name: "Alleppey", lat: 9.49, lng: 76.33, region: "Beaches & South" },
  { name: "Andaman", lat: 11.62, lng: 92.73, region: "Islands" },
  { name: "Nicobar", lat: 7.03, lng: 93.79, region: "Islands" },
  { name: "Lakshadweep", lat: 10.57, lng: 72.64, region: "Islands" },
  { name: "Karnataka", lat: 14.5, lng: 75.5, region: "Beaches & South" },
  { name: "Kerala", lat: 10.5, lng: 76.5, region: "Beaches & South" },
  { name: "Kolkata", lat: 22.57, lng: 88.36, region: "Plains & Heritage" },
];
